version: "3.9"

services:

  redis:
    image: redis:alpine
    volumes:
      - ../../data/redis/:/data/

  django:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../frontend/static/:/usr/src/StoreTracker/frontend/static/
      - ../../media/:/usr/src/StoreTracker/media/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: celery -A core worker -l info -P eventlet
    env_file:
      - ../../.env
    depends_on:
      - django
      - redis