version: "3.9"

services:

  redis:
    image: redis:alpine
    volumes:
      - ../../data/redis/:/data/
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:alpine
    volumes:
      - ../../data/rabbitmq/:/var/lib/rabbitmq
    ports:
      - "5672:5672"

  celery:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ../../:/opt/HealthNutrition-Backend/
    entrypoint: docker/celery_entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.local
      RABBITMQ_HOST: rabbitmq
    env_file:
      - ../../.env
    depends_on:
      - rabbitmq
