PRICE_ROUNDING = 2

PRODUCTS_PAGINATE_BY = 16
PRODUCT_TYPES_PAGINATE_BY = 9

PRODUCTS_ORDERING = ("store__name", "price")
PRODUCT_TYPES_ORDERING = ("-views",)

PRODUCT_VIEW_CACHE_TIME = 60 * 60
PRODUCT_TYPE_VIEW_CACHE_TIME = 60 * 60
