PRICE_ROUNDING = 2

PRODUCTS_PAGINATE_BY = 16
PRODUCT_TYPES_PAGINATE_BY = 9

PRODUCT_TYPES_CACHE_KEY = "popular_product_types"

PRODUCT_TYPES_CACHE_TIME = 60 * 60
PRODUCTS_CACHE_TIME = 60 * 60

PRODUCTS_ORDERING = ("store__name", "price")
PRODUCT_TYPES_ORDERING = ("-views",)
