name: Linters

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ruff linter
        uses: chartboost/ruff-action@v1
        with:
          src: "."

      - name: Black linter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
